[programs.localnet]
mysolana = "4B2EcqWMuDwGjy1aFRMEKrrf7JakJHiJHyeKwv12GZxn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "mocha"
